schedules:
- cron: "30 16 * * 0"
  # 4:30pm UTC every Sunday
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

pr:
- master

variables:
  BUILD_COMMIT: "1.3.0.0"
  UPLOAD_TO_BACKBLAZE: 0
  # Upload to test pipy
  UPLOAD_TO_TEST_PYPI: 0
  # Upload to official pipy repo
  UPLOAD_TO_OFFI_PYPI: 0

jobs:
    # x86_64 linux builds
  - template: azure/posix.yml
    parameters:
      name: linux_x86_64
      vmImage: ubuntu-18.04
      plat: x86_64
      matrix:
        py_3.6_64_manylinux2010:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.6_64_manylinux2014:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"

        py_3.7_64_manylinux2010:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.7_64_manylinux2014:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"

        py_3.8_64_manylinux2010:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.8_64_manylinux2014:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"

        py_3.9_64_manylinux2010:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.9_64_manylinux2014:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"

        py_3.10_64_manylinux2010:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2010"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
        py_3.10_64_manylinux2014:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"

    # x86_64 linux builds
  - template: azure/posix.yml
    parameters:
      name: linux_aarch64
      vmImage: ubuntu-18.04
      plat: aarch64
      matrix:
        py_3.6_aarch64_manylinux2014:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"


        py_3.7_aarch64_manylinux2014:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"


        py_3.8_aarch64_manylinux2014:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"


        py_3.9_aarch64_manylinux2014:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"


        py_3.10_aarch64_manylinux2014:
          MB_PYTHON_VERSION: "3.10"
          MB_ML_VER: "2014"
          DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"






  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.15
      matrix:
        py_3.6_64:
          MB_PYTHON_VERSION: "3.6"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.7_64:
          MB_PYTHON_VERSION: "3.7"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"
          MB_PYTHON_OSX_VER: "10.9"
        py_3.10_64:
          MB_PYTHON_VERSION: "3.10"
          MB_PYTHON_OSX_VER: "10.9"


        # OSX universal2 builds
        py_3.8_universal2:
          MB_PYTHON_VERSION: "3.8"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: universal2
        py_3.9_universal2:
          MB_PYTHON_VERSION: "3.9"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: universal2
        py_3.10_universal2:
          MB_PYTHON_VERSION: "3.10"
          MB_PYTHON_OSX_VER: "10.9"
          PLAT: universal2
