schedules:
- cron: "30 16 * * 0"
  # 4:30pm UTC every Sunday
  displayName: Weekly build
  branches:
    include:
    - master
  always: true

pr:
- master

variables:
  BUILD_COMMIT: "master"

jobs:
  - template: azure/posix.yml
    parameters:
      name: linux
      vmImage: ubuntu-18.04
      matrix:
        # 64-bit linux builds
        py_3.6_64manylinux1:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "1"
        py_3.6_64_manylinux2010:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "2010"
        py_3.6_64_manylinux2014:
          MB_PYTHON_VERSION: "3.6"
          MB_ML_VER: "2014"
          
        py_3.7_64manylinux1:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "1"
        py_3.7_64_manylinux2010:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2010"
        py_3.7_64_manylinux2014:
          MB_PYTHON_VERSION: "3.7"
          MB_ML_VER: "2014"
          
        py_3.8_64manylinux1:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "1"
        py_3.8_64_manylinux2010:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2010"
        py_3.8_64_manylinux2014:
          MB_PYTHON_VERSION: "3.8"
          MB_ML_VER: "2014"
          
        py_3.9_64manylinux1:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "1"
        py_3.9_64_manylinux2010:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2010"
        py_3.9_64_manylinux2014:
          MB_PYTHON_VERSION: "3.9"
          MB_ML_VER: "2014"
                  

        # 32-bit linux builds
        py_3.6_32manylinux1:
          MB_PYTHON_VERSION: "3.6"
          PLAT: "i686"
          MB_ML_VER: "1"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"

        py_3.6_32manylinux2010:
          MB_PYTHON_VERSION: "3.6"
          PLAT: "i686"
          MB_ML_VER: "2010"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"

        py_3.7_32manylinux1:
          MB_PYTHON_VERSION: "3.7"
          PLAT: "i686"
          MB_ML_VER: "1"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"

        py_3.7_32manylinux2010:
          MB_PYTHON_VERSION: "3.7"
          PLAT: "i686"
          MB_ML_VER: "2010"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"

        py_3.8_32manylinux1:
          MB_PYTHON_VERSION: "3.8"
          PLAT: "i686"
          MB_ML_VER: "1"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"

        py_3.8_32manylinux2010:
          MB_PYTHON_VERSION: "3.8"
          PLAT: "i686"
          MB_ML_VER: "2010"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"

        py_3.9_32manylinux1:
          MB_PYTHON_VERSION: "3.9"
          PLAT: "i686"
          MB_ML_VER: "1"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"

        py_3.9_32manylinux2010:
          MB_PYTHON_VERSION: "3.9"
          PLAT: "i686"
          MB_ML_VER: "2010"
          ENV_VARS_PATH: "env_vars_32.sh"
          DOCKER_TEST_IMAGE: "multibuild/xenial_{PLAT}"





  - template: azure/posix.yml
    parameters:
      name: macOS
      vmImage: macOS-10.15
      matrix:
        py_3.6_64:
          MB_PYTHON_VERSION: "3.6"
        py_3.7_64:
          MB_PYTHON_VERSION: "3.7"
        py_3.8_64:
          MB_PYTHON_VERSION: "3.8"
        py_3.9_64:
          MB_PYTHON_VERSION: "3.9"

        py_3.9_universal2:
          MB_PYTHON_VERSION: "3.9"
          PLAT: universal2
