trigger:
  branches:
    include:
      - master

schedules:
  - cron: "30 16 * * 0" # 4:30pm UTC every Sunday
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

parameters:
  - name: BUILD_LINUX
    type: boolean
    default: true
  - name: BUILD_OSX
    type: boolean
    default: true

variables:
  BUILD_COMMIT: "1.3.2.1"
  UPLOAD_TO_TEST_PYPI: 1
  UPLOAD_TO_OFFI_PYPI: 0

jobs:
  # Linux x86_64 builds
  - ${{ if eq(parameters.BUILD_LINUX, true) }}:
    - template: azure/posix.yml
      parameters:
        name: linux_x86_64
        vmImage: ubuntu-latest
        plat: x86_64
        matrix:
          py_3.8_64_manylinux2014:
            MB_PYTHON_VERSION: "3.8"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.9_64_manylinux2014:
            MB_PYTHON_VERSION: "3.9"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.10_64_manylinux2014:
            MB_PYTHON_VERSION: "3.10"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.11_64_manylinux2014:
            MB_PYTHON_VERSION: "3.11"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.12_64_manylinux2014:
            MB_PYTHON_VERSION: "3.12"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.13_64_manylinux2014:
            MB_PYTHON_VERSION: "3.13"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"

  # Linux aarch64 builds
  - ${{ if eq(parameters.BUILD_LINUX, true) }}:
    - template: azure/posix.yml
      parameters:
        name: linux_aarch64
        vmImage: ubuntu-latest
        plat: aarch64
        matrix:
          py_3.8_aarch64_manylinux2014:
            MB_PYTHON_VERSION: "3.8"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.9_aarch64_manylinux2014:
            MB_PYTHON_VERSION: "3.9"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.10_aarch64_manylinux2014:
            MB_PYTHON_VERSION: "3.10"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.11_aarch64_manylinux2014:
            MB_PYTHON_VERSION: "3.11"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.12_aarch64_manylinux2014:
            MB_PYTHON_VERSION: "3.12"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"
          py_3.13_aarch64_manylinux2014:
            MB_PYTHON_VERSION: "3.13"
            MB_ML_VER: "2014"
            DOCKER_TEST_IMAGE: "multibuild/focal_{PLAT}"

  # macOS builds
  - ${{ if eq(parameters.BUILD_OSX, true) }}:
    - template: azure/posix.yml
      parameters:
        name: macOS
        vmImage: macos-latest
        matrix:
          py_3.8_64:
            MB_PYTHON_VERSION: "3.8"
            MB_PYTHON_OSX_VER: "10.9"
          py_3.9_64:
            MB_PYTHON_VERSION: "3.9"
            MB_PYTHON_OSX_VER: "10.9"
          py_3.10_64:
            MB_PYTHON_VERSION: "3.10"
            MB_PYTHON_OSX_VER: "10.9"
          py_3.11_64:
            MB_PYTHON_VERSION: "3.11"
            MB_PYTHON_OSX_VER: "10.9"
          py_3.12_64:
            MB_PYTHON_VERSION: "3.12"
            MB_PYTHON_OSX_VER: "10.9"
          py_3.13_64:
            MB_PYTHON_VERSION: "3.13"
            MB_PYTHON_OSX_VER: "10.9"
          py_3.8_arm64:
            MB_PYTHON_VERSION: "3.8"
            MB_PYTHON_OSX_VER: "10.9"
            PLAT: arm64
          py_3.9_arm64:
            MB_PYTHON_VERSION: "3.9"
            MB_PYTHON_OSX_VER: "10.9"
            PLAT: arm64
          py_3.10_arm64:
            MB_PYTHON_VERSION: "3.10"
            MB_PYTHON_OSX_VER: "10.9"
            PLAT: arm64
          py_3.11_arm64:
            MB_PYTHON_VERSION: "3.11"
            MB_PYTHON_OSX_VER: "10.9"
            PLAT: arm64
          py_3.12_arm64:
            MB_PYTHON_VERSION: "3.12"
            MB_PYTHON_OSX_VER: "10.9"
            PLAT: arm64
          py_3.13_arm64:
            MB_PYTHON_VERSION: "3.13"
            MB_PYTHON_OSX_VER: "10.9"
            PLAT: arm64
