name: Deploy windows wheels and source code

on:
  push:
    branches: [master]

env:
  BUILD_COMMIT: 1.2.7.1
  UPLOAD_TO_BACKBLAZE: 0
  # Upload to test pipy
  UPLOAD_TO_TEST_PYPI: 0
  # Upload to official pipy repo
  UPLOAD_TO_OFFI_PYPI: 0
  GLPK_VERSION: "5.0"
  GLPK_SHA256: 4a1013eebb50f728fc601bdd833b0b2870333c3b3e5a816eeba921d95bec6f15
  OSQP_VERSION: 0.6.2
  GSL_COMMIT_HASH: "f8e56946ce337a5a3f3229821faaf52607842874"

jobs:

  deploy_source_code:

    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive   
          cd kvxopt
          git checkout ${BUILD_COMMIT}

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Install libraries
        run: |
            brew install openblas glpk gsl fftw suite-sparse osqp

      - name: Build 
        run: |
          cd kvxopt
          python setup.py build
          python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          name: kvxopt-source
          path: kvxopt/dist/*.tar.gz

      - name: Publish wheels to PyPI test
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
        run: |
          twine upload --repository testpypi kvxopt/dist/*.tar.gz
        if: ${{ env.UPLOAD_TO_TEST_PYPI == 1 }}

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload kvxopt/dist/*.tar.gz
        if: ${{ env.UPLOAD_TO_OFFI_PYPI == 1 }}

  Build_common_libs:
    runs-on: windows-latest

    strategy:
      matrix:
        ARCH: [x64, x86]
        include:
          - ARCH: x64
            VC_TARGET: 64
            CMAKE_TARGET: x64

          - ARCH: x86
            VC_TARGET: 32
            CMAKE_TARGET: Win32
      
    steps:

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: coreutils unzip git

      - name: Get GSL
        shell: msys2 {0}
        run: |
            git clone --recursive https://github.com/ampl/gsl.git
            cd gsl
            git checkout ${GSL_COMMIT_HASH}
      
      - name: Get GLPK
        shell: msys2 {0}
        run: |
            wget -nv http://ftp.gnu.org/gnu/glpk/glpk-${{ env.GLPK_VERSION }}.tar.gz
            echo "${GLPK_SHA256}  glpk-${{ env.GLPK_VERSION }}.tar.gz" > GLPK.sha256
            shasum -a 256 -c GLPK.sha256
            tar -xf glpk-${{ env.GLPK_VERSION }}.tar.gz

      - name: Get OSQP
        shell: msys2 {0}
        run: |
            git clone --recursive https://github.com/oxfordcontrol/osqp.git
            cd osqp
            git checkout v${{ env.OSQP_VERSION }}

      - name: Cofigure Visual Studio 2019
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ matrix.VC_TARGET }}.bat"
        shell: cmd

      - name: Compile GLPK
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ matrix.VC_TARGET }}.bat"
            cd glpk-${{ env.GLPK_VERSION }}\w64
            cp config_VC config.h
            nmake /f Makefile_VC glpk.lib
            dir
            cd ..\..
        shell: cmd

      - uses: actions/upload-artifact@v2
        with:
          name: glpk-${{ matrix.ARCH }}
          path: |
            glpk-${{ env.GLPK_VERSION }}\w64\*
            glpk-${{ env.GLPK_VERSION }}\src\glpk.h

      - name: Compile OSQP
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ matrix.VC_TARGET }}.bat"
            cd osqp
            mkdir build
            cd build
            cmake -G "Visual Studio 16 2019" -A ${{ matrix.CMAKE_TARGET }} -DCMAKE_INSTALL_PREFIX=dist ..
            cmake --build . --target install
        shell: cmd

      - uses: actions/upload-artifact@v2
        with:
          name: osqp-${{ matrix.ARCH }}
          path: osqp/build/dist/*

      - name: Compile GSL
        run: |
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ matrix.VC_TARGET }}.bat"
            cd gsl
            mkdir build
            cd build
            cmake -G "Visual Studio 16 2019" -A ${{ matrix.CMAKE_TARGET }} -DGSL_INSTALL_MULTI_CONFIG=ON -DBUILD_SHARED_LIBS=ON -DMSVC_RUNTIME_DYNAMIC=ON -DCMAKE_INSTALL_PREFIX=dist ..
            cmake --build . --target install
        shell: cmd

      - uses: actions/upload-artifact@v2
        with:
          name: gsl-${{ matrix.ARCH }}
          path: gsl/build/dist/*

  Build_wheel:
    needs: Build_common_libs
    runs-on: windows-latest
    env:
      KVXOPT_BUILD_GSL: 1
      KVXOPT_BUILD_FFTW: 1
      KVXOPT_BUILD_GLPK: 1
      KVXOPT_BUILD_DSDP: 0
      KVXOPT_MSVC: 1
      KVXOPT_BUILD_OSQP: 1
      SUITESPARSE_VERSION: 5.10.1
      SUITESPARSE_SHA256: acb4d1045f48a237e70294b950153e48dce5b5f9ca8190e86c2b8c54ce00a7ee
      OPENBLAS_VERSION: 0.3.18
      FFTW_VERSION: 3.3.5


    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
        suite-sparse: [src_suitesparse]
        ARCH: [x64, x86]
        include:
        - ARCH: x64
          VC_TARGET: 64
          PYTHON_TARGET: win-amd64
          OPENBLAS_SHA256: 767757039c354b6625c497a856c362546c1b1e7400278ffb40e3b9bf731f3b27
          FFTW_SHA256: cfd88dc0e8d7001115ea79e069a2c695d52c8947f5b4f3b7ac54a192756f439f

        - ARCH: x86
          VC_TARGET: 32
          PYTHON_TARGET: win32
          OPENBLAS_SHA256: c24ecd6e5f561de3861bf714b35e0957a27ee0e03ab4d2867d08377892daf66e
          FFTW_SHA256: 29882a43033c9393479a4df52a2e9120589c06a2b724155b1a682747fa3e57d4

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive      
          cd kvxopt
          git checkout ${{ env.BUILD_COMMIT }}
        shell: cmd

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.ARCH}}

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: coreutils unzip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Get openblas
        shell: msys2 {0}
        run: |
            wget https://github.com/xianyi/OpenBLAS/releases/download/v${OPENBLAS_VERSION}/OpenBLAS-${OPENBLAS_VERSION}-${{matrix.ARCH}}.zip
            wget https://raw.githubusercontent.com/xianyi/OpenBLAS/v${OPENBLAS_VERSION}/LICENSE  -O OpenBLAS_LINCENSE
            echo "${{matrix.OPENBLAS_SHA256}}  OpenBLAS-${OPENBLAS_VERSION}-${{ matrix.ARCH }}.zip" > OpenBLAS.sha256
            sha256sum -c OpenBLAS.sha256
            mkdir OpenBLAS
            unzip OpenBLAS-${OPENBLAS_VERSION}-${{matrix.ARCH}}.zip -d OpenBLAS/
            echo "KVXOPT_BLAS_LIB_DIR=${{ github.workspace}}/OpenBLAS/lib" >> $GITHUB_ENV
            echo "KVXOPT_LAPACK_LIB=libopenblas" >> $GITHUB_ENV
            echo "KVXOPT_BLAS_LIB=libopenblas" >> $GITHUB_ENV

      - name: Get FFTW
        shell: msys2 {0}
        run: |
            wget ftp://ftp.fftw.org/pub/fftw/fftw-${FFTW_VERSION}-dll${{matrix.VC_TARGET}}.zip
            echo "${{matrix.FFTW_SHA256}}  fftw-${FFTW_VERSION}-dll${{ matrix.VC_TARGET }}.zip" > FFTW.sha256
            shasum -a 256 -c FFTW.sha256
            mkdir fftw_lib
            unzip fftw-${FFTW_VERSION}-dll${{matrix.VC_TARGET}}.zip -d fftw_lib/
            echo "KVXOPT_FFTW_LIB_DIR=${{ github.workspace}}/fftw_lib" >> $GITHUB_ENV
            echo "KVXOPT_FFTW_INC_DIR=${{ github.workspace}}/fftw_lib" >> $GITHUB_ENV
            echo "KVXOPT_FFTW_LIB=libfftw3-3" >> $GITHUB_ENV

      - name: Download suite-sparse source
        shell: msys2 {0}
        run: |
            wget https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v${{ env.SUITESPARSE_VERSION }}.tar.gz
            echo "${SUITESPARSE_SHA256}  v${{ env.SUITESPARSE_VERSION }}.tar.gz" > SuiteSparse.sha256
            shasum -a 256 -c SuiteSparse.sha256
            tar -xf v${{ env.SUITESPARSE_VERSION }}.tar.gz
            echo "KVXOPT_SUITESPARSE_SRC_DIR=${{ github.workspace}}/SuiteSparse-${{ env.SUITESPARSE_VERSION }}" >> $GITHUB_ENV
      
      - uses: actions/download-artifact@v2
        with:
          name: glpk-${{ matrix.ARCH }}
          path: glpk_lib

      - name: Set GLPK path
        shell: msys2 {0}
        run: |
            echo "KVXOPT_GLPK_LIB_DIR=${{ github.workspace}}\glpk_lib\w64" >> $GITHUB_ENV
            echo "KVXOPT_GLPK_INC_DIR=${{ github.workspace}}\glpk_lib\src" >> $GITHUB_ENV
      
      - uses: actions/download-artifact@v2
        with:
          name: osqp-${{ matrix.ARCH }}
          path: osqp_lib

      - name: Set OSQP path
        shell: msys2 {0}
        run: |
            echo "KVXOPT_OSQP_LIB_DIR=${{ github.workspace}}\osqp_lib\lib" >> $GITHUB_ENV
            echo "KVXOPT_OSQP_INC_DIR=${{ github.workspace}}\osqp_lib\include\osqp" >> $GITHUB_ENV

      - name: Create .lib import files for FFTW
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars${{ matrix.VC_TARGET }}.bat"
          cd fftw_lib
          lib /machine:${{ matrix.ARCH }} /def:libfftw3-3.def
        shell: cmd

      - uses: actions/download-artifact@v2
        with:
          name: gsl-${{ matrix.ARCH }}
          path: gsl_lib

      - name: Set GSL path
        shell: msys2 {0}
        run: |
            echo "KVXOPT_GSL_LIB_DIR=${{ github.workspace}}\gsl_lib\lib\Debug" >> $GITHUB_ENV
            echo "KVXOPT_GSL_INC_DIR=${{ github.workspace}}\gsl_lib\include" >> $GITHUB_ENV

      - name: Build wheel
        run: |
          cd kvxopt
          python setup.py build
          copy ${{ github.workspace}}\OpenBLAS\bin\libopenblas.dll build\lib.${{ matrix.PYTHON_TARGET }}-${{ matrix.python-version }}\kvxopt
          copy ${{ github.workspace}}\gsl_lib\bin\Debug\gsl.dll build\lib.${{ matrix.PYTHON_TARGET }}-${{ matrix.python-version }}\kvxopt
          copy ${{ github.workspace}}\gsl_lib\bin\Debug\gslcblas.dll build\lib.${{ matrix.PYTHON_TARGET }}-${{ matrix.python-version }}\kvxopt
          copy ${{ github.workspace}}\fftw_lib\libfftw3-3.dll build\lib.${{ matrix.PYTHON_TARGET }}-${{ matrix.python-version }}\kvxopt
          copy OpenBLAS_LINCENSE build\lib.${{ matrix.PYTHON_TARGET }}-${{ matrix.python-version }}\kvxopt
          python setup.py bdist_wheel
        shell: cmd

      - uses: actions/upload-artifact@v2
        with:
          name: windows-${{ matrix.ARCH }}-${{ matrix.python-version }}-wheel
          path: kvxopt/dist/*.whl


  Test_and_deploy:
    runs-on: windows-latest
    needs: Build_wheel

    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
        ARCH: [x64, x86]

    steps:
      - uses: actions/checkout@v2

      - name: Checkout submodules
        run: |
          git submodule update --init --recursive      
          cd kvxopt
          git checkout ${{ env.BUILD_COMMIT }}
        shell: cmd

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.ARCH}}

      - name: Install python testing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov coveralls twine numpy


      - uses: actions/download-artifact@v2
        with:
          name: windows-${{ matrix.ARCH }}-${{ matrix.python-version }}-wheel

      - name: Test
        run: |
            pip install --no-index --find-links . kvxopt
            python -c 'from kvxopt import blas,lapack,cholmod,umfpack,klu,glpk,osqp'
            py.test --cov=kvxopt kvxopt\tests

      - name: Upload to BACKBLAZE
        env:
          BACKBLAZE_KEYID: ${{ secrets.BACKBLAZE_KEYID }}
          BACKBLAZE_APPKEY: ${{ secrets.BACKBLAZE_APPKEY }}
        run: |
          pip install boto3

          for /r %%f in (*.whl) do python s3_upload.py %%f

        shell: cmd
        if: ${{ env.UPLOAD_TO_BACKBLAZE == 1 }}

      - name: Publish wheels to PyPI test
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_TEST_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_PASSWORD }}
        run: |
          twine upload --repository testpypi *.whl
        if: ${{ env.UPLOAD_TO_TEST_PYPI == 1 }}

      - name: Publish wheels to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload *.whl
        if: ${{ env.UPLOAD_TO_OFFI_PYPI == 1 }}
